export const NOTES_LIST_REQUEST = "NOTE_LIST_REQUEST";
export const NOTES_LIST_SUCCESS = "NOTE_LIST_SUCCESS";
export const NOTES_LIST_FAILURE = "NOTE_LIST_FAILURE";

export const NOTES_CREATE_REQUEST = "NOTE_CREATE_REQUEST";
export const NOTES_CREATE_SUCCESS = "NOTE_CREATE_SUCCESS";
export const NOTES_CREATE_FAILURE = "NOTE_CREATE_FAILURE";

export const NOTES_UPDATE_REQUEST = "NOTE_UPDATE_REQUEST";
export const NOTES_UPDATE_SUCCESS = "NOTE_UPDATE_SUCCESS";
export const NOTES_UPDATE_FAILURE = "NOTE_UPDATE_FAILURE";

export const NOTES_DELETE_REQUEST = "NOTE_DELETE_REQUEST";
export const NOTES_DELETE_SUCCESS = "NOTE_DELETE_SUCCESS";
export const NOTES_DELETE_FAILURE = "NOTE_DELETE_FAILURE";
